### PR TITLE
Emergency Hooter Feature Added With Sound And FlashLight

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
Related Issue: #60 

issue - #60 

Closes: #60 

### Describe the changes you've made

Introduce the Emergency Hooter Feature with Sound And FlashLight.

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## Mention any unusual behaviour of your code (Write NA if not)
Must try in Physical Device by installing the apk or connect it with IDE to test it...
Don't try it in Emulator as Emulator has no flashlight.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)

Demo Video Prove: https://drive.google.com/file/d/1jeSKPl0F4ZxxgFBA7j_m8brfSuorgOAi/view?usp=sharing

### To test sound with flashlight, make sure test it on Physical Device but not in Emulator.

***Button Added With Named as `Hooter` in Emergency Dashboard.***

I am also a GSSOC21 participant..... Please raise the required labels(present in the related issue) related to that program...

Hope you review it and merge it soon @hiashutoshsingh @shagun25

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
Hello @shagun25 @hiashutoshsingh ... Please review and merge this pull request.....Thank u

**Comment by SamarpanCoder2002** [comment]
@hiashutoshsingh @shagun25 .... Please review and merge it..... Hope you respond soon.....

**Review by hiashutoshsingh — APPROVED** [review]
Thanks for your contribution.

**Comment by SamarpanCoder2002** [comment]
Hello @hiashutoshsingh @shagun25.... Why not you raise the labels required for GSSOC21 and level3 related to that pull request......??? It's compulsory for that program... Please raise the corresponding labels related to that issue

**Comment by hiashutoshsingh** [comment]
> Hello @hiashutoshsingh @shagun25.... Why not you raise the labels required for GSSOC21 and level3 related to that issue......??? It's compulsory for that program... Please raise the corresponding labels related to that issue

Thanks for reminding me.

**Comment by SamarpanCoder2002** [comment]
> > Hello @hiashutoshsingh @shagun25.... Why not you raise the labels required for GSSOC21 and level3 related to that issue......??? It's compulsory for that program... Please raise the corresponding labels related to that issue
> 
> Thanks for reminding me.

Thanks for that

**Pull request merged**
