### PR TITLE
Welcome-bot

### PR DESCRIPTION
**Pull request by Vrushti24**
## Related Issue 

- Info about the related issue 

Closes:  #2 
### Describe the changes you've made
Added a welcome bot
Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by hiashutoshsingh** [comment]
Great work! @Vrushti24 
Can you also add the **issue link** to the description? It would be a great help for the reviewer.

**Comment by Vrushti24** [comment]
yeah but which description @hiashutoshsingh ?

**Comment by Vrushti24** [comment]
Issue #2 this one right?

**Comment by hiashutoshsingh** [comment]
> Issue #2 this one right?


Yup this one, just write this issue in the description right above. I think you missed it.
e.g: Closes: #2 
@Vrushti24 
Screenshot 2021-03-16 at 4 24 26 PM

**Comment by Vrushti24** [comment]
Oh..I m sorry I will add that @hiashutoshsingh

**Comment by hiashutoshsingh** [comment]
> Oh..I m sorry I will add that @hiashutoshsingh

Thanks! Please do.

**Review by hiashutoshsingh — APPROVED** [review]
LGTM!

**Pull request merged**
